// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikiMovies.Data;

#nullable disable

namespace WikiMovies.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220811044612_UpdateMigration")]
    partial class UpdateMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WikiMovies.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NameCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameCategory = "Accion",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            NameCategory = "Drama",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            NameCategory = "Ciencia Ficcion",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            NameCategory = "Anime",
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            NameCategory = "Comedia",
                            Status = true
                        });
                });

            modelBuilder.Entity("WikiMovies.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 0,
                            CategoryId = 3,
                            Name = "Constantine"
                        },
                        new
                        {
                            Id = 2,
                            Age = 0,
                            CategoryId = 2,
                            Name = "Hasta el ultimo hombre"
                        },
                        new
                        {
                            Id = 3,
                            Age = 0,
                            CategoryId = 5,
                            Name = "Jonny English"
                        });
                });

            modelBuilder.Entity("WikiMovies.Models.Movie", b =>
                {
                    b.HasOne("WikiMovies.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
